In [1]:
import pandas as pd
from mtga_viz import *

In [2]:
# Loading the collected data
df = pd.read_csv('../data/metagame_challenge/challenge_test_file.csv')

In [10]:
# Homogenising decks (i.e. Izzet -> UR, GB -> BG, etc. Lower case everything)
df_clean= clean_raw_csv(df, user_deck_col='user_deck', oppo_deck_col='oppo_deck')
df_clean.head(10)

,message_time_stamp,user_name,run_result,user_deck,oppo_deck,result_vs_oppo
0,2026-05-09T00:08:13.889000+00:00,greasypeezy,4-1,wr energy,ur sneak and show,2-0
1,2026-05-09T00:08:13.889000+00:00,greasypeezy,4-1,wr energy,ur tempo,2-0
2,2026-05-09T00:08:13.889000+00:00,greasypeezy,4-1,wr energy,mono g landfall,2-0
3,2026-05-09T00:08:13.889000+00:00,greasypeezy,4-1,wr energy,mono b stompy,2-0
4,2026-05-09T00:08:13.889000+00:00,greasypeezy,4-1,wr energy,wbr energy,1-2
5,2026-05-09T00:15:19.958000+00:00,geckos7777,7-0,br aggro,mono b stompy,2-1
6,2026-05-09T00:15:19.958000+00:00,geckos7777,7-0,br aggro,casual,2-0
7,2026-05-09T00:15:19.958000+00:00,geckos7777,7-0,br aggro,ub reanimator,2-0
8,2026-05-09T00:15:19.958000+00:00,geckos7777,7-0,br aggro,ub tempo,2-1
9,2026-05-09T00:15:19.958000+00:00,geckos7777,7-0,br aggro,ur sneak and show,2-0

In [4]:
# This function will extract the list of most played. It uses user_decks to calculate the intersection with most seen decks in the oppo_deck column
most_played_decks, common_deck_counting = explore_most_played_decks(df_clean, 'user_deck', 'oppo_deck')

In [5]:
# This will tell you the most repeated decks in both user and oppo columns
list_to_table(most_played_decks,3)

         bg bonds              bg lands          br aggro
        br breach               br burn        br goblins
         br goyfs         br moonshadow         brg goyfs
     cavern goyfs        eldrazi stompy      mono b aggro
mono b reanimator           mono b scam      mono r aggro
      mono r burn mono r eldrazi stompy    mono r goblins
   mono r prowess         mono r stompy   mono red stompy
         rg lands               ub mill     ub reanimator
      ub shredder              ub tempo               ubg
      ur affinity            ur prowess ur sneak and show
         ur tempo             urg tempo        wbr energy
        wr energy              wu tempo        wub energy
  wub necro sorin              wug nadu               NaN

In [6]:
# Alternatively, one can also explore all the unique deck names for user_deck with:
list_to_table(df_clean['user_deck'].unique(),3)

       bg bonds          bg lands              br aggro
      br breach           br burn            br goblins
       br goyfs     br moonshadow             brg goyfs
 brg reanimator      cavern goyfs        eldrazi stompy
   mono b aggro mono b reanimator           mono b scam
   mono r aggro       mono r burn mono r eldrazi stompy
 mono r goblins    mono r prowess         mono r stompy
mono red stompy     mono w humans    pensive frog combo
       rg lands        ub control               ub mill
  ub reanimator       ub shredder              ub tempo
            ubg        ubg shadow           ur affinity
        ur burn        ur prowess     ur sneak and show
       ur tempo         urg beans             urg tempo
     wbr energy         wr energy              wu tempo
     wub energy   wub necro sorin              wug nadu
    wur control         wur tempo                   NaN

In [ ]:
# With previous information, one can establish categories to assign archetypes to each deck. Here one can define which decks belong to which archetypes. No need to match full names. It could be single words in the full string.

# Better to have these definitions in a .py file to easily call them from other notebooks

TEMPO = ['tempo', 'shadow']
AGGRO = ['energy', 'aggro', 'bonds', 'shredder', 'burn', 'prowess', 'humans', 'goblins', 'affinity']
BLUE_COMBO = ['ub reanimator', 'show and tell', 'sneak and show', 'mill', 'nadu']
FAST_COMBO = ['breach', 'sorin', 'muxus']
CONTROL = ['control', 'beans']
STOMPY = ['stompy', 'prison']
MIDRANGE = ['goyf', 'lands']

dictionaries = {'tempo': TEMPO,
                'aggro' : AGGRO, 
                'blue_combo': BLUE_COMBO, 
                'fast_combo':FAST_COMBO,
                'stompy': STOMPY,
                'control': CONTROL,
                'midrange': MIDRANGE}

In [8]:
# With previous information, we can then add the archetype tags. One can also extract total amount of trophies and amount of runs
df_w_extra_columns, amount_trophies, run_counting = create_new_columns(
    df_clean, 'message_time_stamp', 
    run_col='run_result', 
    source_cols=['user_deck', 'oppo_deck'], 
    keyword_dict=dictionaries, 
    new_cols=['user_deck_arch', 'oppo_deck_arch'], 
    def_tag='other')

In [9]:
df_w_extra_columns.head(5)

,message_time_stamp,user_name,run_result,user_deck,oppo_deck,result_vs_oppo,user_deck_arch,oppo_deck_arch
0,2026-05-09T00:08:13.889000+00:00,greasypeezy,4-1,wr energy,ur sneak and show,2-0,aggro,blue_combo
1,2026-05-09T00:08:13.889000+00:00,greasypeezy,4-1,wr energy,ur tempo,2-0,aggro,tempo
2,2026-05-09T00:08:13.889000+00:00,greasypeezy,4-1,wr energy,mono g landfall,2-0,aggro,other
3,2026-05-09T00:08:13.889000+00:00,greasypeezy,4-1,wr energy,mono b stompy,2-0,aggro,stompy
4,2026-05-09T00:08:13.889000+00:00,greasypeezy,4-1,wr energy,wbr energy,1-2,aggro,aggro